name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --dev

      - run: pipenv run black --check .
      - run: pipenv run pytest
